
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kenlm_KenlmJNI */

#ifndef _Included_kenlm_KenlmJNI
#define _Included_kenlm_KenlmJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kenlm_KenlmJNI
 * Method:    ConfigNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kenlm_KenlmJNI_ConfigNew
  (JNIEnv *, jclass);

/*
 * Class:     kenlm_KenlmJNI
 * Method:    ConfigDelete
 * Signature: (J)V